name: Deploy Next.js Site to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.8.0" # Set this to your Node.js version

      - name: Build and Export Next.js Project
        run: |
          npm install
          npm run build

      - name: Move Output to docs Folder
        run: |
          mkdir -p ./docs
          cp -r ./dist/* ./docs

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Deploy vite example site to GitHub Pages" -a
          git push
